# gears
APP_ID = "7505e2f9997e37f849f142da258f93b0"
LINK = "https://api.worldoftanks.eu/wot/account/list/?application_id=7505e2f9997e37f849f142da258f93b0&search="

tmain = "https://tomato.gg/"
# =====


# compare
t_sOverall_1 = "https://tomato.gg/_next/data/"
t_sOverall_2 = "/en/tank-performance/overall/EU.json"

t_sRecent_1 = "https://tomato.gg/_next/data/"
t_sRecent_2 = "/en/tank-performance/recent/EU.json"

t_pOverall_1 = "https://api.tomato.gg/dev/api-v2/player/overall/eu/"
# =====


# maps
t_pmap_l_1 = "https://api.tomato.gg/dev/api-v2/player/combined-battles/"
t_pmap_l_2 = "?pageSize=10000&sortBy=battle_time"
# =====


# moe
p_moe_l = "https://poliroid.me/gunmarks/api/v2/data/eu/vehicles"
mastery_l = "https://poliroid.me/mastery/api/v2/data/eu/vehicles"
t_pOverall_l = "https://api.tomato.gg/dev/api-v2/player/overall/eu/"
# =====


# server
t_sOverall_l_1 = "https://tomato.gg/_next/data/"
t_sOverall_l_2 = "/en/tank-performance/overall/EU.json"

t_sRecent_l_1 = "https://tomato.gg/_next/data/"
t_sRecent_l_2 = "/en/tank-performance/recent/EU.json"

economics_l_1 = "https://tomato.gg/_next/data/"
economics_l_2 = "/en/economics/all.json?mode=all"
# =====


# onslaught
t_onsl_l_1 = "https://api.tomato.gg/dev/api-v2/player/combined-battles/"
t_onsl_l_2 = "?battleType=comp7&pageSize=1000&sortBy=battle_time"
t_onslT_l = "https://api.tomato.gg/dev/api-v2/player/onslaught/"
# =====